
server:
    servlet:
        encoding:
        # 한글깨짐 처리 
            force-response: true

# Spring Data Source 설정 
spring:

    output:
        ansi:
            enabled: always 

    # 데이터 베이스 
    datasource:
        url: jdbc:mysql://0:3306/teamdata?userSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
        username: teamdb
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver

    #  데이터 베이스 커넥션 
    jpa:
        hibernate:
            ddl-auto: update 
        properties:
            hibernate:
                show_sql: true 
                format_sql: true 
                dialect: org.hibernate.dialect.MySQLDialect

    # mustache (1. 루트폴더 변경, 2. 타임리프 캐시 설정 변경)
    mustache:
        prefix: classpath:templates/
        check-template-location: true
        suffix: .html
        cache: false

    mvc:
        static-path-pattern: /static/**
cloud:
    aws:
        credentials:
            accessKey: A
            secretKey: d
        region:
            static: ap-northeast-2
        stack:
            auto: false
application:
    bucket:
        name: playdataproject